"""
Nginx Configuration Generator for PyRest framework.
Generates nginx configuration for routing to embedded and isolated apps.
"""

import logging
from pathlib import Path
from typing import List, Optional, Dict, Any
from datetime import datetime

from .config import get_config
from .app_loader import AppConfig

logger = logging.getLogger("pyrest.nginx_generator")


class NginxGenerator:
    """
    Generates nginx configuration files for PyRest apps.
    """
    
    def __init__(self, output_dir: str = "nginx"):
        self.config = get_config()
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_upstream_config(
        self,
        main_port: int,
        isolated_apps: List[AppConfig]
    ) -> str:
        """Generate nginx upstream blocks."""
        lines = [
            "# PyRest Upstream Configuration",
            f"# Generated: {datetime.now().isoformat()}",
            "",
            "# Main PyRest server",
            "upstream pyrest_main {",
            f"    server 127.0.0.1:{main_port};",
            "    keepalive 64;",
            "}",
            ""
        ]
        
        # Add upstream for each isolated app
        for app in isolated_apps:
            if app.port:
                lines.extend([
                    f"# Isolated app: {app.name}",
                    f"upstream pyrest_{app.name} {{",
                    f"    server 127.0.0.1:{app.port};",
                    f"    keepalive 32;",
                    "}",
                    ""
                ])
        
        return "\n".join(lines)
    
    def generate_location_config(
        self,
        base_path: str,
        embedded_apps: List[AppConfig],
        isolated_apps: List[AppConfig]
    ) -> str:
        """Generate nginx location blocks for routing."""
        lines = [
            "# PyRest Location Configuration",
            f"# Generated: {datetime.now().isoformat()}",
            "",
            "# Proxy settings",
            "proxy_http_version 1.1;",
            "proxy_set_header Host $host;",
            "proxy_set_header X-Real-IP $remote_addr;",
            "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
            "proxy_set_header X-Forwarded-Proto $scheme;",
            "proxy_set_header Upgrade $http_upgrade;",
            'proxy_set_header Connection "upgrade";',
            "proxy_connect_timeout 60s;",
            "proxy_send_timeout 60s;",
            "proxy_read_timeout 60s;",
            "proxy_buffering off;",
            ""
        ]
        
        # Add locations for isolated apps first (more specific routes)
        for app in isolated_apps:
            if app.port:
                prefix = app.prefix.rstrip("/")
                lines.extend([
                    f"# Isolated app: {app.name}",
                    f"location {base_path}{prefix}/ {{",
                    f"    proxy_pass http://pyrest_{app.name};",
                    "}",
                    ""
                ])
        
        # Add catch-all location for main server (embedded apps)
        lines.extend([
            "# Main PyRest server (embedded apps + framework endpoints)",
            f"location {base_path}/ {{",
            "    proxy_pass http://pyrest_main;",
            "}",
            ""
        ])
        
        return "\n".join(lines)
    
    def generate_full_config(
        self,
        main_port: int,
        embedded_apps: List[AppConfig],
        isolated_apps: List[AppConfig],
        server_name: str = "localhost",
        listen_port: int = 80
    ) -> str:
        """Generate complete nginx server configuration."""
        base_path = self.config.base_path
        
        lines = [
            "# PyRest Nginx Configuration",
            f"# Generated: {datetime.now().isoformat()}",
            "#",
            "# This file is auto-generated by PyRest.",
            "# Include this file in your nginx.conf or copy to sites-available.",
            "#",
            "# Installation:",
            "#   1. Copy to /etc/nginx/sites-available/pyrest.conf",
            "#   2. ln -s /etc/nginx/sites-available/pyrest.conf /etc/nginx/sites-enabled/",
            "#   3. nginx -t && systemctl reload nginx",
            "",
            ""
        ]
        
        # Upstreams
        lines.append(self.generate_upstream_config(main_port, isolated_apps))
        
        # Server block
        lines.extend([
            "",
            "server {",
            f"    listen {listen_port};",
            f"    listen [::]:{listen_port};",
            f"    server_name {server_name};",
            "",
            "    # Logging",
            "    access_log /var/log/nginx/pyrest_access.log;",
            "    error_log /var/log/nginx/pyrest_error.log;",
            "",
            "    # Proxy settings",
            "    proxy_http_version 1.1;",
            "    proxy_set_header Host $host;",
            "    proxy_set_header X-Real-IP $remote_addr;",
            "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
            "    proxy_set_header X-Forwarded-Proto $scheme;",
            "    proxy_set_header Upgrade $http_upgrade;",
            '    proxy_set_header Connection "upgrade";',
            "    proxy_connect_timeout 60s;",
            "    proxy_send_timeout 60s;",
            "    proxy_read_timeout 60s;",
            "    proxy_buffering off;",
            ""
        ])
        
        # Add locations for isolated apps first (more specific routes)
        for app in isolated_apps:
            if app.port:
                prefix = app.prefix.rstrip("/")
                lines.extend([
                    f"    # Isolated app: {app.name}",
                    f"    location {base_path}{prefix}/ {{",
                    f"        proxy_pass http://pyrest_{app.name};",
                    "    }",
                    ""
                ])
        
        # Add catch-all location for main server
        lines.extend([
            "    # Main PyRest server (embedded apps + framework endpoints)",
            f"    location {base_path}/ {{",
            "        proxy_pass http://pyrest_main;",
            "    }",
            "",
            "    # Health check endpoint",
            "    location /nginx-health {",
            "        access_log off;",
            '        return 200 "healthy\\n";',
            "        add_header Content-Type text/plain;",
            "    }",
            "}",
            ""
        ])
        
        return "\n".join(lines)
    
    def generate_and_save(
        self,
        embedded_apps: List[AppConfig],
        isolated_apps: List[AppConfig],
        filename: str = "pyrest_generated.conf"
    ) -> Path:
        """Generate nginx config and save to file."""
        main_port = self.config.port
        config_content = self.generate_full_config(
            main_port=main_port,
            embedded_apps=embedded_apps,
            isolated_apps=isolated_apps
        )
        
        output_path = self.output_dir / filename
        
        with open(output_path, "w") as f:
            f.write(config_content)
        
        logger.info(f"Generated nginx configuration: {output_path}")
        return output_path
    
    def generate_app_summary(
        self,
        embedded_apps: List[AppConfig],
        isolated_apps: List[AppConfig]
    ) -> str:
        """Generate a summary of app routing for reference."""
        base_path = self.config.base_path
        main_port = self.config.port
        
        lines = [
            "# PyRest App Routing Summary",
            f"# Generated: {datetime.now().isoformat()}",
            "",
            "## Framework Endpoints",
            f"  GET  {base_path}/           - API info",
            f"  GET  {base_path}/health     - Health check",
            f"  GET  {base_path}/apps       - List apps",
            f"  POST {base_path}/auth/login - JWT login",
            f"  GET  {base_path}/auth/azure/login - Azure AD login",
            "",
            "## Embedded Apps (port {main_port})",
        ]
        
        for app in embedded_apps:
            prefix = app.prefix.rstrip("/")
            lines.append(f"  - {app.name}: {base_path}{prefix}/")
        
        if not embedded_apps:
            lines.append("  (none)")
        
        lines.extend([
            "",
            "## Isolated Apps"
        ])
        
        for app in isolated_apps:
            prefix = app.prefix.rstrip("/")
            lines.append(f"  - {app.name}: {base_path}{prefix}/ (port {app.port})")
        
        if not isolated_apps:
            lines.append("  (none)")
        
        return "\n".join(lines)


# Singleton instance
_nginx_generator: Optional[NginxGenerator] = None


def get_nginx_generator() -> NginxGenerator:
    """Get the singleton NginxGenerator instance."""
    global _nginx_generator
    if _nginx_generator is None:
        _nginx_generator = NginxGenerator()
    return _nginx_generator
